[workspace]
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
publish_timeout = "10m"
semver_check = false
git_release_enable = true
git_tag_enable = true

[[package]]
name = "garc"
changelog_path = "CHANGELOG.md"
publish = true
